#!/bin/sh

# PROVIDE: nsd-dynamic-updater
# REQUIRE: LOGIN nsd
# KEYWORD: shutdown

. /etc/rc.subr

name="nsd-dynamic-updater"
rcvar="${name}_enable"

load_rc_config $name

export RACK_ENV=production

pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-c -f -P ${pidfile} -u sinatra -r /usr/local/bin/ruby /root/nsd-dynamic-updater/app.rb"

run_rc_command "$1"
